Repository kubermatic/community-components, pull requests merged in 2021-09, with the labels that each got.

#30 Added Prometheus Service Gateway and Thanos-seed-ingress charts
  components/component-deploy.sh
Labels: dco-signoff: yes, size/XS

#32 Create kubeone-add-dns-name.md
  runbook/kubeone-add-dns-name.md
Labels: lgtm, dco-signoff: no, size/M

#33 Create kubeone_ip_change.md
  runbook/kubeone_ip_change.md
Labels: dco-signoff: yes, lgtm, size/M

#35 Transfer baremetal examples from kubermatic-labs/kubermatic-demo
  README.md
  examples/baremetal/kkp/kubadm-manual/Dockerfile
  examples/baremetal/kkp/kubadm-manual/README.md
  examples/baremetal/kkp/kubadm-manual/kubeadm-install.sh
  examples/baremetal/kkp/kubeadm-multi-client/.gitignore
  examples/baremetal/kkp/kubeadm-multi-client/01_setup-install-multi-client-ssh.sh
  examples/baremetal/kkp/kubeadm-multi-client/02_setup-join-multi-client-ssh.sh
  examples/baremetal/kkp/kubeadm-multi-client/README.md
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/Dockerfile
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/README.md
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/kubeadm-generator-install.sh
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/kubeadm-setup-ubuntu.sh
  examples/baremetal/kkp/kubeadm-multi-client/maintenance/01_exec-on-all-hosts.sh
  examples/baremetal/kkp/kubeadm-multi-client/maintenance/exec.sh
  examples/baremetal/kkp/kubeadm-multi-client/tf-infra/.gitignore
  examples/baremetal/kkp/kubeadm-multi-client/tf-infra/README.md
  examples/baremetal/kkp/kubeadm-multi-client/tf-infra/credentials/vsphere.customer_user.source.sh
  examples/baremetal/kkp/kubeadm-multi-client/tf-infra/main.tf
  examples/baremetal/kkp/kubeadm-multi-client/tf-infra/outputs.tf
  examples/baremetal/kkp/kubeadm-multi-client/tf-infra/terraform.tfvars
  examples/baremetal/kkp/kubeadm-multi-client/tf-infra/variables.tf
  examples/baremetal/kkp/kubeadm-multi-client/tf-infra/versions.tf
  examples/baremetal/kubeone/vsphere-static-machines/Makefile
  examples/baremetal/kubeone/vsphere-static-machines/addons/00_storage_class.yaml
  examples/baremetal/kubeone/vsphere-static-machines/addons/10-metallb-namespace.yaml
  examples/baremetal/kubeone/vsphere-static-machines/addons/11_metallb-secret.yaml
  examples/baremetal/kubeone/vsphere-static-machines/addons/12_metallb.yaml
  examples/baremetal/kubeone/vsphere-static-machines/addons/13_metallb-config.yaml
  examples/baremetal/kubeone/vsphere-static-machines/addons/30_ingress_deploy.yaml
  examples/baremetal/kubeone/vsphere-static-machines/addons/40_kubernetes_dashboard.yaml
  examples/baremetal/kubeone/vsphere-static-machines/addons/41_kubernetes_dashboard_user.yaml
  examples/baremetal/kubeone/vsphere-static-machines/kubeone.yaml
  examples/baremetal/kubeone/vsphere-static-machines/tf-infra/README.md
  examples/baremetal/kubeone/vsphere-static-machines/tf-infra/etc_gobetween.tpl
  examples/baremetal/kubeone/vsphere-static-machines/tf-infra/gobetween.sh
  examples/baremetal/kubeone/vsphere-static-machines/tf-infra/main.tf
  examples/baremetal/kubeone/vsphere-static-machines/tf-infra/outputs.tf
  examples/baremetal/kubeone/vsphere-static-machines/tf-infra/terraform.tfvars
  examples/baremetal/kubeone/vsphere-static-machines/tf-infra/variables.tf
  examples/baremetal/kubeone/vsphere-static-machines/tf-infra/versions.tf
Labels: dco-signoff: yes, size/XXL
