Repository kubermatic/community-components, pull requests merged in 2021-02, with the labels that each got.

#13 Add SSHD to container
  helper/kubeone-tool-container/Dockerfile
  helper/kubeone-tool-container/README.md
  helper/kubeone-tool-container/startup.sh
Labels: dco-signoff: yes, lgtm, size/M

#10 extend setup-checklist: split KKP/kubeone, add baremetal requirements
  README.md
  helper/kubeone-tool-container/README.md
  knowledge-base/setup-checklist/kkp/README.md
  knowledge-base/setup-checklist/kkp/azure-requirments.md
  knowledge-base/setup-checklist/kkp/baremetal-requirements.md
  knowledge-base/setup-checklist/kkp/openstack-requirements.md
  knowledge-base/setup-checklist/kkp/vsphere-requirements.md
  knowledge-base/setup-checklist/kubeone/README.md
  knowledge-base/setup-checklist/kubeone/kubeone-baremetal-requirements.md
Labels: dco-signoff: yes, lgtm, size/L

#14 Refactor kubeone tooling
  helper/kubeone-tool-container/.bashrc
  helper/kubeone-tool-container/Dockerfile
  helper/kubeone-tool-container/Makefile
  helper/kubeone-tool-container/startup.sh
  helper/kubeone-tool-container/terraform_libraries.tf
Labels: dco-signoff: yes, size/L

#15 Kubelb addon
  kubermatic-addons/addon-manifests/kubelb.yaml
  kubermatic-addons/custom-addon/kubelb/kubelb-agent.yaml
Labels: dco-signoff: yes, lgtm, size/L
