Repository kubermatic/community-components, pull requests merged in 2021-12, with the labels that each got.

#46 fix krew and update kubeone to latest release 1.3.2
  helper/kubeone-tool-container/Dockerfile
  helper/kubeone-tool-container/Makefile
Labels: dco-signoff: yes, size/XS

#44 Add KKP addon for flux2
  README.md
  kubermatic-addons/Dockerfile
  kubermatic-addons/Makefile
  kubermatic-addons/addon-manifests/flux2.yaml
  kubermatic-addons/custom-addon/flux2/00-manifest.yaml
  kubermatic-addons/custom-addon/flux2/01-bootstrap.yaml
  kubermatic-addons/kustomize/flux2/kustomization.yaml
  kubermatic-addons/kustomize/flux2/patches/add-node-selector.yaml
  kubermatic-addons/kustomize/flux2/transformers/label-transformer.yaml
  kubermatic-addons/logos/flux-horizontal-color.png
Labels: dco-signoff: yes, size/XXL, lgtm

#45 Add argocd addon
  README.md
  kubermatic-addons/Makefile
  kubermatic-addons/addon-manifests/argocd.yaml
  kubermatic-addons/custom-addon/argocd/00-manifest.yaml
  kubermatic-addons/custom-addon/argocd/01-bootstrap.yaml
  kubermatic-addons/kustomize/argocd/kustomization.yaml
  kubermatic-addons/kustomize/argocd/patches/add-configmap-init-container.yaml
  kubermatic-addons/kustomize/argocd/patches/delete-dynamic-configmaps.yaml
  kubermatic-addons/kustomize/argocd/resources/namespace.yaml
  kubermatic-addons/logos/argo-horizontal-color.png
Labels: dco-signoff: yes, size/XXL, lgtm

#48 Add SSH support to ArgoCD addon
  kubermatic-addons/addon-manifests/argocd.yaml
  kubermatic-addons/custom-addon/argocd/00-manifest.yaml
  kubermatic-addons/custom-addon/argocd/01-bootstrap.yaml
  kubermatic-addons/kustomize/argocd/kustomization.yaml
  kubermatic-addons/kustomize/argocd/patches/add-ssh-known-hosts-init-container.yaml
Labels: dco-signoff: yes, lgtm, size/M

#47 add option to use ssh repos too
  kubermatic-addons/addon-manifests/argocd.yaml
  kubermatic-addons/custom-addon/argocd/01-bootstrap.yaml
Labels: dco-signoff: yes, size/S
