Repository kubermatic/community-components, pull requests merged in 2021-01, with the labels that each got.

#7 Add OpenEBS Kubermatic addon
  README.md
  kubermatic-addons/addon-manifests/openebs.yaml
  kubermatic-addons/custom-addon/openebs/openebs-operator.yaml
  kubermatic-addons/custom-addon/openebs/storageclass.yaml
Labels: dco-signoff: yes, lgtm, size/XL

#9 Add AMD GPU plugin Kubermatic addon
  README.md
  kubermatic-addons/addon-manifests/amd-gpu.yaml
  kubermatic-addons/custom-addon/amd-gpu/k8s-ds-amdgpu-dp.yaml
Labels: dco-signoff: yes, lgtm, size/M

#8 Updating Kubeone Tooling Container
  helper/kubeone-tool-container/Dockerfile
  helper/kubeone-tool-container/README.md
Labels: dco-signoff: yes, lgtm, size/M

#11 Add Terraform Provider to tooling Container
  helper/kubeone-tool-container/Dockerfile
  helper/kubeone-tool-container/terraform_libraries.tf
Labels: dco-signoff: yes, size/M

#12 Add kubeflow addon
  README.md
  kubermatic-addons/addon-manifests/kubeflow.yaml
  kubermatic-addons/custom-addon/kubeflow/amd-gpu-dp.yaml
  kubermatic-addons/custom-addon/kubeflow/amd-gpu-labeller.yaml
  kubermatic-addons/custom-addon/kubeflow/kubeflow-controller.yaml
  kubermatic-addons/custom-addon/kubeflow/kubeflow.yaml
  kubermatic-addons/custom-addon/kubeflow/node-feature-discovery.yaml
  kubermatic-addons/custom-addon/kubeflow/nvidia-gpu-operator.yaml
Labels: dco-signoff: yes, lgtm, size/XXL
