Repository kubermatic/community-components, pull requests merged in 2021-07, with the labels that each got.

#25 Runbook for MetalLB based connection drops related IPVS strict ARP mode
  README.md
  kubermatic-addons/custom-addon/kube-proxy-ipvs-patch/README.md
  kubermatic-addons/custom-addon/kube-proxy-ipvs-patch/clusterrolebinding.yaml
  kubermatic-addons/custom-addon/kube-proxy-ipvs-patch/configmap.yaml
  kubermatic-addons/custom-addon/kube-proxy-ipvs-patch/daemonset.yaml
  kubermatic-addons/custom-addon/kube-proxy-ipvs-patch/serviceaccount.yaml
  runbook/metallb/helper/arp-status-script.sh
  runbook/metallb/helper/get-all-ip-interfaces-ssh.sh
  runbook/metallb/helper/tcp-dump-arp.sh
  runbook/metallb/metallb-service-connection-drops-ipvs-strict-arp.md
Labels: dco-signoff: yes, size/XL

#26 add runbook how to fix Crash Looping Prometheus at KKP user cluster namespace
  README.md
  runbook/user-cluster-prometheus.md
Labels: dco-signoff: yes, lgtm, size/L

#27 Fix addon path for some Kubermatic addons
  README.md
Labels: dco-signoff: yes, size/XS

#28 add S3 syncer and Azure Gatewayproxy
  README.md
  components/s3/s3-syncer-aws-cli/Chart.yaml
  components/s3/s3-syncer-aws-cli/templates/aws.client.yaml
  components/s3/s3-syncer-aws-cli/templates/deployment-azure-gateway.yaml
  components/s3/s3-syncer-aws-cli/templates/pvc.transfer.data.yaml
  components/s3/s3-syncer-aws-cli/templates/s3.credentials.cm.yaml
  components/s3/s3-syncer-aws-cli/templates/secret-azure-storage.yaml
  components/s3/s3-syncer-aws-cli/templates/svc-azure-gateway.yaml
  components/s3/s3-syncer-aws-cli/values.yaml
Labels: dco-signoff: yes, size/L
