Repository kubermatic/community-components, pull requests merged in 2022-05, with the labels that each got.

#59 Add OWNERS and OWNER_ALIASES for community components repo
  OWNERS
  OWNERS_ALIASES
Labels: dco-signoff: yes, lgtm, approved, size/XS

#53 add Expiring client certificate
  README.md
  runbook/.assets/KubeClientCertificateExpiration.png
  runbook/k8s-kubeconfig-expiring-failure.md
Labels: dco-signoff: yes, size/L, lgtm

#55 Add How to collect the provisioned CPU/Memory
  README.md
  knowledge-base/.assets/prometheus_cpu_mem_metric_average_comparison.png
  knowledge-base/how-to-collect-cluster-cpu-memory.md
Labels: dco-signoff: yes, size/L

#56 Changes to upgrade kubeone to 1.4.2
  helper/kubeone-tool-container/.bashrc
  helper/kubeone-tool-container/.p10k.zsh
  helper/kubeone-tool-container/.zshrc
  helper/kubeone-tool-container/Dockerfile
  helper/kubeone-tool-container/Makefile
Labels: dco-signoff: yes, size/XXL

#60 Ntp syc & metallbv2
  kubermatic-addons/custom-addon/metallb-v2/12_metallb-system.yaml
  kubermatic-addons/custom-addon/ntp-sync/90_ntp_daemon_set.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#61 Added uuid-runtime for uuidgen command support
  helper/kubeone-tool-container/Dockerfile
Labels: dco-signoff: yes, lgtm, approved, size/XS

#62 upgrade k1 tooling container to k1 version 1.4.3
  helper/kubeone-tool-container/Makefile
Labels: dco-signoff: yes, lgtm, approved, size/XS
