Repository kubermatic/community-components, pull requests merged in 2022-10, with the labels that each got.

#67 add first working cluster creation by cluster templates
  components/api/cluster-management-by-api/common-scripts/_common.sh
  components/api/cluster-management-by-api/common-scripts/cluster-delete-all.sh
  components/api/cluster-management-by-api/common-scripts/cluster-delete.sh
  components/api/cluster-management-by-api/common-scripts/cluster-template-create-instance.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#71 update k1 tooling to 1.5.1
  helper/kubeone-tool-container/Makefile
Labels: dco-signoff: yes, approved, size/XS

#72 Update / Fix different addons to make them smooth
  README.md
  kubermatic-addons/addon-manifests/amd-gpu.yaml
  kubermatic-addons/addon-manifests/argocd.yaml
  kubermatic-addons/addon-manifests/cert-manager.yaml
  kubermatic-addons/addon-manifests/cluster-autoscaler.yaml
  kubermatic-addons/addon-manifests/docker-pre-pull.yaml
  kubermatic-addons/addon-manifests/echoserver.yaml
  kubermatic-addons/addon-manifests/flux2.yaml
  kubermatic-addons/addon-manifests/gatekepper.yaml
  kubermatic-addons/addon-manifests/ingress-nginx.yaml
  kubermatic-addons/addon-manifests/kubelb.yaml
  kubermatic-addons/addon-manifests/metallb.yaml
  kubermatic-addons/addon-manifests/nfs-csi.yaml
  kubermatic-addons/addon-manifests/openebs.yaml
  kubermatic-addons/addon-manifests/trident-installer.yaml
  kubermatic-addons/archive/addon-manifests-kkp-2.20/gatekepper.yaml
  kubermatic-addons/custom-addon/docker-pre-pull/91_docker_pre_pull_daemon_set.yaml
  kubermatic-addons/custom-addon/echoserver/echo.server.deplyment.yaml
  kubermatic-addons/custom-addon/nfs/nfs-csi-driver.yaml
  kubermatic-addons/custom-addon/nfs/nfs-sc-config.yaml
  kubermatic-addons/logos/README.md
  kubermatic-addons/logos/docker-prepull.png
  kubermatic-addons/logos/kubelb-agent.png
  kubermatic-addons/logos/nfs-storage-logo-sm.png
Labels: dco-signoff: yes, lgtm, size/XL, approved

#73 Fixed End of Line
  kubermatic-addons/addon-manifests/amd-gpu.yaml
  kubermatic-addons/addon-manifests/docker-pre-pull.yaml
  kubermatic-addons/addon-manifests/metallb.yaml
  kubermatic-addons/custom-addon/echoserver/echo.server.deplyment.yaml
  kubermatic-applications/eclipse-che-app.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S
