Repository kubermatic/community-components, pull requests merged in 2022-01, with the labels that each got.

#38 add vmware-exporter helm chart
  components/component-deploy.sh
  components/vmware-exporter/Chart.yaml
  components/vmware-exporter/templates/NOTES.txt
  components/vmware-exporter/templates/_helpers.tpl
  components/vmware-exporter/templates/configmap.yaml
  components/vmware-exporter/templates/deployment.yaml
  components/vmware-exporter/templates/ingress.yaml
  components/vmware-exporter/templates/secret.yaml
  components/vmware-exporter/templates/service.yaml
  components/vmware-exporter/values.yaml
Labels: dco-signoff: yes, size/L, lgtm

#40 Add Cluster Management by API with Bash
  README.md
  components/api/cluster-management-by-api/.gitignore
  components/api/cluster-management-by-api/README.md
  components/api/cluster-management-by-api/common-scripts/.kkp-env.sh
  components/api/cluster-management-by-api/common-scripts/_common.sh
  components/api/cluster-management-by-api/common-scripts/addon-delete-all.sh
  components/api/cluster-management-by-api/common-scripts/addon-delete.sh
  components/api/cluster-management-by-api/common-scripts/addon-deploy.sh
  components/api/cluster-management-by-api/common-scripts/cluster-apply.sh
  components/api/cluster-management-by-api/common-scripts/cluster-delete-all.sh
  components/api/cluster-management-by-api/common-scripts/cluster-delete.sh
  components/api/cluster-management-by-api/common-scripts/kubeconfig-get.sh
  components/api/cluster-management-by-api/common-scripts/md-apply-yaml.sh
  components/api/cluster-management-by-api/common-scripts/md-apply.sh
  components/api/cluster-management-by-api/example-run-env-md-yaml/.kkp-env.sh
  components/api/cluster-management-by-api/example-run-env-md-yaml/Makefile
  components/api/cluster-management-by-api/example-run-env-md-yaml/kubevirt-with-autoscaling/addon-cluster-autoscaler.json
  components/api/cluster-management-by-api/example-run-env-md-yaml/kubevirt-with-autoscaling/addon-ingress-nginx.json
  components/api/cluster-management-by-api/example-run-env-md-yaml/kubevirt-with-autoscaling/cluster.json
  components/api/cluster-management-by-api/example-run-env-md-yaml/kubevirt-with-autoscaling/md-small.yaml
  components/api/cluster-management-by-api/example-run-env-md-yaml/kubevirt-with-autoscaling/md.yaml
  components/api/cluster-management-by-api/example-run-env/.kkp-env.sh
  components/api/cluster-management-by-api/example-run-env/Makefile
  components/api/cluster-management-by-api/example-run-env/kubevirt/addon-cluster-autoscaler.json
  components/api/cluster-management-by-api/example-run-env/kubevirt/addon-ingress-nginx.json
  components/api/cluster-management-by-api/example-run-env/kubevirt/cluster.json
  components/api/cluster-management-by-api/example-run-env/kubevirt/machine_deployment_ubuntu.json
  components/api/cluster-management-by-api/example-run-env/vsphere/addon-ingress-nginx.json
  components/api/cluster-management-by-api/example-run-env/vsphere/addon-metallb.json
  components/api/cluster-management-by-api/example-run-env/vsphere/cluster-with-initial-node-deployment.json
  components/api/cluster-management-by-api/example-run-env/vsphere/cluster.json
  components/api/cluster-management-by-api/example-run-env/vsphere/machine_deployment_centos.json
  components/api/cluster-management-by-api/example-run-env/vsphere/machine_deployment_flatcar.json
  components/api/cluster-management-by-api/example-run-env/vsphere/machine_deployment_ubuntu.json
Labels: dco-signoff: yes, size/XXL

#51 update kubeone tooling container to 1.3.3
  helper/kubeone-tool-container/Dockerfile
  helper/kubeone-tool-container/Makefile
Labels: dco-signoff: yes, lgtm, size/XS

#50 For KKP 2.19 add helm dependcy build to installation script
  helper/kubermatic-installer-script/kubermatic-deploy.sh
Labels: dco-signoff: yes, lgtm, size/XS
