Repository kubermatic/community-components, pull requests merged in 2022-12, with the labels that each got.

#77 add rclone s3 syncer
  components/component-deploy.sh
  components/rclone-s3-syncer/Chart.yaml
  components/rclone-s3-syncer/templates/cronjob.yaml
  components/rclone-s3-syncer/templates/source-ca-bundle-cm.yaml
  components/rclone-s3-syncer/templates/source-secret.yaml
  components/rclone-s3-syncer/templates/target-ca-bundle-cm.yaml
  components/rclone-s3-syncer/templates/target-secret.yaml
  components/rclone-s3-syncer/values.yaml
Labels: dco-signoff: yes, size/L, lgtm, approved

#76 Added default values.yaml configuration for the applications
  components/eclipse-che/Chart.yaml
  components/eclipse-che/templates/org_v2_checluster.yaml
  kubermatic-applications/argocd-app.yaml
  kubermatic-applications/echoserver-app.yaml
  kubermatic-applications/eclipse-che-app.yaml
  kubermatic-applications/flux2-app.yaml
  kubermatic-applications/harbor-app.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#80 Added support for Openstack provider in Tooling container terraform
  helper/kubeone-tool-container/Makefile
  helper/kubeone-tool-container/terraform_libraries.tf
Labels: dco-signoff: yes, lgtm, approved, size/XS

#79 Update ConfigMap of ingress-nginx-controller to avoid upload limit
  kubermatic-addons/custom-addon/ingress-nginx/deploy.yaml
Labels: dco-signoff: yes, lgtm, needs-ok-to-test, approved, size/XS

#75 add velero addon
  kubermatic-addons/addon-manifests/velero.yaml
  kubermatic-addons/custom-addon/velero/00_crds.yaml
  kubermatic-addons/custom-addon/velero/10_namespace.yaml
  kubermatic-addons/custom-addon/velero/config.yaml
  kubermatic-addons/custom-addon/velero/daemonset.yaml
  kubermatic-addons/custom-addon/velero/deployment.yaml
  kubermatic-addons/custom-addon/velero/rbac.yaml
  kubermatic-addons/custom-addon/velero/secrets.yaml
  kubermatic-addons/custom-addon/velero/serviceaccount.yaml
Labels: dco-signoff: yes, size/XXL, lgtm, approved
