Repository kubermatic/community-components, pull requests merged in 2023-02, with the labels that each got.

#86 Added cilium CLI to kubeone tooling container
  helper/kubeone-tool-container/Dockerfile
Labels: dco-signoff: yes, approved, size/S

#78 Added KeyCloak setup example yaml files for KKP
  README.md
  components/id-management/keycloak/kubermatic.example.yaml
  components/id-management/keycloak/values.example.yaml
  components/id-management/keycloak/values.seed.example.yaml
  components/id-management/keycloak/values.seed.user-mla.example.yaml
Labels: dco-signoff: yes, size/L, lgtm, approved

#88 Update kubelb agent to kubelb-ccm
  kubermatic-addons/addon-manifests/kubelb.yaml
  kubermatic-addons/archive/addon-manifests-kkp-2.20/kubelb.yaml
  kubermatic-addons/custom-addon/kubelb/kubelb-agent.yaml
  kubermatic-addons/custom-addon/kubelb/kubelb-ccm.yaml
Labels: dco-signoff: yes, size/L, lgtm, approved

#85 Added custom application definition for Canal setup
  components/canal/Chart.yaml
  components/canal/templates/canal.yaml
  components/canal/values.yaml
  kubermatic-addons/Makefile
  kubermatic-applications/README.md
  kubermatic-applications/canal.yaml
Labels: dco-signoff: yes, size/XXL

#89 update kubeadm client example kkp
  examples/baremetal/kkp/kubeadm-multi-client/.gitignore
  examples/baremetal/kkp/kubeadm-multi-client/01_setup-install-multi-client-ssh.sh
  examples/baremetal/kkp/kubeadm-multi-client/02_create_kubeadm_join_token.sh
  examples/baremetal/kkp/kubeadm-multi-client/02_setup-join-multi-client-ssh.sh
  examples/baremetal/kkp/kubeadm-multi-client/03_setup-join-multi-client-ssh.sh
  examples/baremetal/kkp/kubeadm-multi-client/04_upgrade-kubeadm-multi-client-ssh.sh
  examples/baremetal/kkp/kubeadm-multi-client/99_reset-multi-client-ssh.sh
  examples/baremetal/kkp/kubeadm-multi-client/README.md
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/Dockerfile-rockylinux
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/Dockerfile-ubuntu
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/README.md
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/kubeadm-generator-install.sh
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/kubeadm-reset.sh
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/kubeadm-setup-rockylinux.sh
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/kubeadm-setup-ubuntu.sh
  examples/baremetal/kkp/kubeadm-multi-client/kubeadm/kubeadm-upgrade.sh
  examples/baremetal/kkp/kubeadm-multi-client/maintenance/01_exec-on-all-hosts.sh
  examples/baremetal/kkp/kubeadm-multi-client/maintenance/exec.sh
Labels: dco-signoff: yes, size/XXL, approved
