Repository kubermatic/community-components, pull requests merged in 2024-02, with the labels that each got.

#114 Update README.md
  components/capacity-monitoring/README.md
Labels: dco-signoff: yes, lgtm, approved, ok-to-test, size/XS

#115 Update cm.grafana-dashboard-definitions.yaml
  components/vmware-exporter/templates/cm.grafana-dashboard-definitions.yaml
Labels: dco-signoff: yes, lgtm, approved, ok-to-test, size/S

#117 Upate K1 Tooling: fix root bash + add ngrok + modify ssh-debug manifest
  container/kubeone-tool-container/.bashrc
  container/kubeone-tool-container/Dockerfile
  container/kubeone-tool-container/Makefile
  container/kubermatic-dev-ui/Makefile
  helper/ssh-debug/README.md
  helper/ssh-debug/deployment.ssh.debug.yaml
  helper/ssh-debug/deployment.ssh.k1.debug.yaml
  helper/ssh-debug/secrect.ssh.files.yaml
  helper/ssh-debug/secrect.ssh.key.yaml
Labels: dco-signoff: yes, size/L, lgtm, approved
