Repository kubermatic/community-components, pull requests merged in 2024-07, with the labels that each got.

#128 y
  container/kubeone-tool-container/.gitconfig
  container/kubeone-tool-container/Makefile
Labels: dco-signoff: yes, size/XS

#129 Add external-dns as KKP Application
  README.md
  kubermatic-applications/external-dns-app.yaml
Labels: dco-signoff: yes, size/M

#112 Added ArgoCD template for creating seed environment and other helpful components
  ArgoCD-managed-seed/.helmignore
  ArgoCD-managed-seed/Chart.yaml
  ArgoCD-managed-seed/README.md
  ArgoCD-managed-seed/proposed-dir-structure/Makefile
  ArgoCD-managed-seed/proposed-dir-structure/dev/seed1/.gitkeep
  ArgoCD-managed-seed/proposed-dir-structure/dev/seed2/.gitkeep
  ArgoCD-managed-seed/proposed-dir-structure/prod/seed1/.gitkeep
  ArgoCD-managed-seed/proposed-dir-structure/prod/seed2/.gitkeep
  ArgoCD-managed-seed/templates/_helpers.tpl
  ArgoCD-managed-seed/templates/argocd-apps-backup.yaml
  ArgoCD-managed-seed/templates/argocd-apps-kkp-core.yaml
  ArgoCD-managed-seed/templates/argocd-apps-logging.yaml
  ArgoCD-managed-seed/templates/argocd-apps-monitoring.yaml
  ArgoCD-managed-seed/templates/argocd-apps-storage.yaml
  ArgoCD-managed-seed/templates/argocd-apps-usermla.yaml
  ArgoCD-managed-seed/values.yaml
  README.md
  components/api/cluster-management-by-api/common-scripts/_common.sh
  components/api/cluster-management-by-api/common-scripts/alertmanager-rules-deploy.sh
  components/api/cluster-management-by-api/common-scripts/cluster-apply.sh
  components/api/cluster-management-by-api/example-run-env/vsphere/alertrules-customnodeexporter.yaml
  components/user-cluster-alertmanager-alerts/README.md
  components/user-cluster-alertmanager-alerts/alertrules-argocd.yaml
  components/user-cluster-alertmanager-alerts/alertrules-customnodeexporter.yaml
  components/user-cluster-alertmanager-alerts/alertrules-machinecontroller.yaml
  components/user-cluster-alertmanager-alerts/alertrules-metallb.yaml
  components/user-cluster-alertmanager-alerts/alertrules-minio.yaml
  components/user-cluster-alertmanager-alerts/alertrules-pod-cronjob.yaml
  components/user-cluster-grafana-dashboards/README.md
  components/user-cluster-grafana-dashboards/minio-dashboard-cm.yaml
  components/user-cluster-grafana-dashboards/nginx.yaml
  components/user-cluster-grafana-dashboards/request-handling-performance.yaml
Labels: dco-signoff: yes, size/XXL, lgtm, approved
