Repository kubermatic/community-components, pull requests merged in 2024-10, with the labels that each got.

#130 check if velero crd directory exists
  helper/kubermatic-installer-script/kubermatic-deploy.sh
Labels: dco-signoff: yes, lgtm, approved, size/XS

#131 update k1 and add cleanup helper
  README.md
  container/kubeone-tool-container/Makefile
  helper/kube-node-cleanup.sh
Labels: dco-signoff: yes, size/M

#132 Flatcar Linux timesyncd & resolved overwrites
  kubermatic-addons/custom-addon/flatcar-linux-resolved-overwrite/flatcar_linux_resolved_overwrite_daemonset.yaml
  kubermatic-addons/custom-addon/flatcar_linux_timesyncd_overwrite/flatcar_linux_timesyncd_overwrite_daemonset.yaml
Labels: dco-signoff: yes, size/L, lgtm, needs-ok-to-test, approved
